### ISSUE TITLE
SONOS not longer working

### ISSUE THREAD

**Issue by dor4711** [fhem/fhem-docker#235]
**Describe the bug**
After upgrade to 4 (latest) SONOS is not longer working.

**To Reproduce**
1. After upgrade to latest 
2. `Cannot load module SONOS
setuuid: Please define XXXX first
Cannot load module SONOSPLAYER
setuuid: Please define XXXX first`

**Expected behavior**
It should work as before.

**Logs**
```
2024.06.02 08:20:44.165 1: reload: Error:Modul 00_SONOS deactivated:
 This Perl not built to support threads
Compilation failed in require at ./FHEM/00_SONOS.pm line 137, <$fh> line 73.
BEGIN failed--compilation aborted at ./FHEM/00_SONOS.pm line 137, <$fh> line 73.

2024.06.02 08:20:44.165 0: This Perl not built to support threads
Compilation failed in require at ./FHEM/00_SONOS.pm line 137, <$fh> line 73.
BEGIN failed--compilation aborted at ./FHEM/00_SONOS.pm line 137, <$fh> line 73.

2024.06.02 08:20:44.179 1: reload: Error:Modul 21_SONOSPLAYER deactivated:
 syntax error at ./FHEM/21_SONOSPLAYER.pm line 216, near "SONOS_Log undef"
Global symbol "$def" requires explicit package name (did you forget to declare "my $def"?) at ./FHEM/21_SONOSPLAYER.pm line 224, <$fh> line 77.
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/21_SONOSPLAYER.pm line 235, <$fh> line 77.
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/21_SONOSPLAYER.pm line 236, <$fh> line 77.
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/21_SONOSPLAYER.pm line 238, <$fh> line 77.
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/21_SONOSPLAYER.pm line 239, <$fh> line 77.
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/21_SONOSPLAYER.pm line 242, <$fh> line 77.
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/21_SONOSPLAYER.pm line 244, <$fh> line 77.
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/21_SONOSPLAYER.pm line 245, <$fh> line 77.
syntax error at ./FHEM/21_SONOSPLAYER.pm line 248, near "}"
./FHEM/21_SONOSPLAYER.pm has too many errors.
```

**Desktop (please complete the following information):**
 - raspberry pi 4
 - Rocky Linux release 9.4
 - docker 26.1.3
 - fhem/fhem latest

**Comment by dor4711** [comment]
Ok it works with `fhem/fhem:4-threaded-bullseye`.

Nevertheless it is surprising that a standard module is not working with "latest".

**Comment by sidey79** [comment]
AS noted in the logs, the sonos module needs a special compiled perl(threaded).

Because of this module, the threaded variant is provided.
